"""
Feature Engineering & Data Preprocessing for LSTM.

Transforms raw OHLCV data into ML-ready sequences with:
- Technical indicators (returns, volatility, RSI, MACD signals)
- Rolling statistical features
- MinMax scaling with inverse transform support
- Sliding window sequence generation
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from loguru import logger
from sklearn.preprocessing import MinMaxScaler

from config.settings import config


class DataPreprocessor:
    """
    Transforms raw market data into normalised feature sequences
    for the LSTM model.
    """

    # Feature columns generated by this preprocessor
    FEATURE_COLS = [
        "close_norm",       # normalised close  [0, 1]  — via _price_scaler
        "volume_norm",      # normalised volume [0, 1]  — via _volume_scaler
        "returns",          # log returns        [-1, 1] — via _feature_scaler
        "volatility_20",    # 20-period vol      [-1, 1] — via _feature_scaler
        "rsi_14",           # 14-period RSI      [-1, 1] — via _feature_scaler
        "macd_signal",      # MACD histogram     [-1, 1] — via _feature_scaler
        "volume_ratio",     # vol / 20-MA vol    [-1, 1] — via _feature_scaler
    ]

    # Raw indicator columns that need feature_scaler (NOT close_norm/volume_norm)
    _RAW_INDICATOR_COLS = [
        "returns", "volatility_20", "rsi_14", "macd_signal", "volume_ratio",
    ]

    def __init__(self) -> None:
        self.model_cfg = config.model
        self.seq_length = self.model_cfg.sequence_length
        self.forecast_horizon = self.model_cfg.forecast_horizon

        # Scalers — fitted during training, reused in inference
        self._price_scaler = MinMaxScaler(feature_range=(0, 1))  # global fallback
        self._volume_scaler = MinMaxScaler(feature_range=(0, 1))
        self._feature_scaler = MinMaxScaler(feature_range=(-1, 1))

        # Per-symbol price scalers for multi-symbol training.
        # Each symbol's close prices are normalised independently so the LSTM
        # sees [0,1] = symbol's own price range, not a merged cross-symbol range.
        self._symbol_price_scalers: Dict[str, MinMaxScaler] = {}

        self._is_fitted = False

    @property
    def n_features(self) -> int:
        return len(self.FEATURE_COLS)

    # ── Feature Engineering ───────────────────────────────────
    def compute_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Compute all features from raw OHLCV data."""
        df = df.copy()

        # Normalise timestamps to tz-naive before sorting to prevent
        # "can't compare offset-naive and offset-aware datetimes" errors
        # when mixing historical (tz-aware) and live (tz-naive) data.
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True).dt.tz_localize(None)

        df = df.sort_values("timestamp").reset_index(drop=True)

        # Log returns
        df["returns"] = np.log(df["close"] / df["close"].shift(1))

        # Rolling volatility (20-period)
        df["volatility_20"] = df["returns"].rolling(window=20).std()

        # RSI (14-period)
        df["rsi_14"] = self._compute_rsi(df["close"], period=14)

        # MACD histogram
        df["macd_signal"] = self._compute_macd(df["close"])

        # Volume ratio (current / 20-period MA)
        vol_ma = df["volume"].rolling(window=20).mean()
        df["volume_ratio"] = df["volume"] / vol_ma.clip(lower=1)

        # Normalised placeholders (filled during fit/transform)
        df["close_norm"] = df["close"]
        df["volume_norm"] = df["volume"].astype(float)

        # Drop initial NaN rows from rolling computations
        # The longest warm-up is 26 (MACD slow) + 9 (signal) = ~35 rows
        df = df.dropna(subset=["returns", "volatility_20", "rsi_14", "macd_signal", "volume_ratio"]).reset_index(drop=True)

        return df

    def _compute_rsi(self, prices: pd.Series, period: int = 14) -> pd.Series:
        """Compute Relative Strength Index using Wilder's smoothing."""
        delta = prices.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        # Use EWM for Wilder's smoothing (equivalent to alpha=1/period)
        avg_gain = gain.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()
        avg_loss = loss.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()

        rs = avg_gain / avg_loss.clip(lower=1e-10)
        rsi = 100 - (100 / (1 + rs))
        # Normalise RSI to [-1, 1]
        return (rsi - 50) / 50

    def _compute_macd(
        self,
        prices: pd.Series,
        fast: int = 12,
        slow: int = 26,
        signal: int = 9,
    ) -> pd.Series:
        """Compute MACD histogram (normalised)."""
        ema_fast = prices.ewm(span=fast, adjust=False).mean()
        ema_slow = prices.ewm(span=slow, adjust=False).mean()
        macd_line = ema_fast - ema_slow
        signal_line = macd_line.ewm(span=signal, adjust=False).mean()
        histogram = macd_line - signal_line

        # Normalise by price level
        return histogram / prices.clip(lower=1e-10)

    # ── Fit & Transform ──────────────────────────────────────
    def fit(self, df: pd.DataFrame) -> "DataPreprocessor":
        """Fit scalers on training data."""
        features = self.compute_features(df)

        # Global price/volume scalers (fallback for unknown symbols)
        self._price_scaler.fit(features[["close"]].values)
        self._volume_scaler.fit(features[["volume"]].values)

        # Per-symbol price scalers — each symbol gets its own [0,1] range
        if "symbol" in features.columns:
            for sym in features["symbol"].unique():
                sym_close = features.loc[
                    features["symbol"] == sym, "close"
                ].values.reshape(-1, 1)
                scaler = MinMaxScaler(feature_range=(0, 1))
                scaler.fit(sym_close)
                self._symbol_price_scalers[sym] = scaler
                logger.debug(
                    f"Per-symbol scaler {sym}: "
                    f"min=₹{scaler.data_min_[0]:,.2f}, "
                    f"max=₹{scaler.data_max_[0]:,.2f}"
                )

        # Feature scaler for raw indicator columns ONLY → [-1, 1]
        raw_matrix = features[self._RAW_INDICATOR_COLS].values
        self._feature_scaler.fit(raw_matrix)

        self._is_fitted = True
        logger.info(
            f"Preprocessor fitted on {len(features)} samples, "
            f"{self.n_features} features, "
            f"{len(self._symbol_price_scalers)} symbol scalers"
        )
        return self

    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """Transform data using fitted scalers.

        Pipeline:
        1. compute_features() → raw OHLCV → technical indicators
        2. _price_scaler  → close to close_norm  [0, 1]  (clamped)
        3. _volume_scaler → volume to volume_norm [0, 1]  (clamped)
        4. _feature_scaler → raw indicators to [-1, 1]   (clamped)
        5. NaN/Inf guard on final output

        close_norm and volume_norm are NOT double-scaled — they keep
        their dedicated scaler values so inverse_transform_price()
        can directly invert through _price_scaler.
        """
        assert self._is_fitted, "Preprocessor must be fitted before transform"

        features = self.compute_features(df)

        # ── Step 1: Scale close → [0, 1] per-symbol ──
        if "symbol" in features.columns and self._symbol_price_scalers:
            # Per-symbol normalisation
            close_norm_vals = np.zeros(len(features), dtype=np.float64)
            for sym, grp_idx in features.groupby("symbol").groups.items():
                scaler = self._symbol_price_scalers.get(sym, self._price_scaler)
                sym_close = features.loc[grp_idx, "close"].values.reshape(-1, 1)
                scaled = scaler.transform(sym_close).flatten()
                close_norm_vals[grp_idx.values] = scaled
            features["close_norm"] = np.clip(close_norm_vals, 0, 1)
        else:
            # Single-symbol or fallback: use per-symbol scaler if available.
            # If exactly one symbol scaler exists and no symbol column,
            # it's single-symbol inference — use that scaler.
            scaler = self._price_scaler
            if len(self._symbol_price_scalers) == 1:
                scaler = next(iter(self._symbol_price_scalers.values()))
            elif len(self._symbol_price_scalers) > 1 and "symbol" not in features.columns:
                # Can't determine which scaler to use without symbol column.
                # Fall through to global scaler.
                pass

            close_scaled = scaler.transform(
                features[["close"]].values
            ).flatten()
            features["close_norm"] = np.clip(close_scaled, 0, 1)

        # ── Step 2: Scale volume → [0, 1] ──
        volume_scaled = self._volume_scaler.transform(
            features[["volume"]].values
        ).flatten()
        volume_min, volume_max = self._volume_scaler.feature_range
        features["volume_norm"] = np.clip(volume_scaled, volume_min, volume_max)

        # ── Step 3: Scale raw indicator columns → [-1, 1] ──
        raw_matrix = features[self._RAW_INDICATOR_COLS].values
        scaled_raw = self._feature_scaler.transform(raw_matrix)

        # Clamp to prevent OOD extrapolation
        feat_min, feat_max = self._feature_scaler.feature_range
        scaled_raw = np.clip(scaled_raw, feat_min, feat_max)

        for i, col in enumerate(self._RAW_INDICATOR_COLS):
            features[col] = scaled_raw[:, i]

        # ── Step 4: Final NaN/Inf guard on all feature columns ──
        for col in self.FEATURE_COLS:
            features[col] = features[col].replace(
                [np.inf, -np.inf], np.nan
            ).fillna(0.0)

        return features

    def fit_transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """Fit and transform in one step."""
        self.fit(df)
        return self.transform(df)

    # ── Sequence Generation ──────────────────────────────────
    def create_sequences(
        self, df: pd.DataFrame
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Create input-output sequence pairs for LSTM training.

        When the DataFrame contains multiple symbols, sequences are
        generated PER SYMBOL to prevent cross-symbol contamination
        at symbol boundaries.

        Returns:
            X: shape (n_samples, seq_length, n_features)
            y: shape (n_samples, forecast_horizon)  — normalised close prices
        """
        all_X, all_y = [], []

        # Generate sequences per-symbol to avoid cross-symbol leakage
        if "symbol" in df.columns:
            groups = df.groupby("symbol")
        else:
            groups = [("_single", df)]

        for sym, sym_df in groups:
            feature_matrix = sym_df[self.FEATURE_COLS].values
            close_norm = sym_df["close_norm"].values

            for i in range(len(feature_matrix) - self.seq_length - self.forecast_horizon + 1):
                all_X.append(feature_matrix[i : i + self.seq_length])
                all_y.append(
                    close_norm[
                        i + self.seq_length : i + self.seq_length + self.forecast_horizon
                    ]
                )

        X = np.array(all_X, dtype=np.float32)
        y = np.array(all_y, dtype=np.float32)

        logger.info(f"Created {len(X)} sequences: X={X.shape}, y={y.shape}")
        return X, y

    def create_single_sequence(
        self, df: pd.DataFrame
    ) -> Optional[np.ndarray]:
        """
        Create a single sequence from the most recent data for real-time inference.

        Returns:
            shape (1, seq_length, n_features) or None if insufficient data.
        """
        features = self.transform(df)
        feature_matrix = features[self.FEATURE_COLS].values

        if len(feature_matrix) < self.seq_length:
            return None

        seq = feature_matrix[-self.seq_length :]
        return np.array([seq], dtype=np.float32)

    # ── Inverse Transform ────────────────────────────────────
    def inverse_transform_price(
        self, normalised: np.ndarray, symbol: Optional[str] = None
    ) -> np.ndarray:
        """Convert model output (close_norm in [0,1] space) back to actual price.

        Uses the per-symbol scaler when available. If no per-symbol scaler
        exists (symbol wasn't in training data), falls back to a dynamically
        fitted scaler if one was registered, or the global scaler.
        """
        scaler = self._price_scaler  # global fallback
        if symbol and symbol in self._symbol_price_scalers:
            scaler = self._symbol_price_scalers[symbol]
        elif symbol:
            # No per-symbol scaler for this symbol — log a warning
            logger.warning(
                f"No per-symbol scaler for {symbol}, using global scaler. "
                f"Predictions may be inaccurate. Re-train to fix."
            )
        return scaler.inverse_transform(
            normalised.reshape(-1, 1)
        ).flatten()

    def register_live_scaler(
        self, symbol: str, close_values: np.ndarray
    ) -> None:
        """Dynamically fit a per-symbol scaler from live buffer data.

        Called by the inference engine when it detects a symbol with
        no saved scaler, using the historical warm-up data in the buffer.
        This prevents massive prediction divergence for symbols that
        weren't in the training set.
        """
        if symbol in self._symbol_price_scalers:
            return  # Already have one
        if len(close_values) < 10:
            return  # Not enough data

        scaler = MinMaxScaler(feature_range=(0, 1))
        scaler.fit(close_values.reshape(-1, 1))
        self._symbol_price_scalers[symbol] = scaler
        logger.info(
            f"🔧 Dynamically fitted scaler for {symbol}: "
            f"min=₹{scaler.data_min_[0]:,.2f}, "
            f"max=₹{scaler.data_max_[0]:,.2f}"
        )

    # ── Serialisation ────────────────────────────────────────
    def get_state(self) -> Dict:
        """Get scaler state for saving — includes ALL scalers for inference parity."""
        state = {"is_fitted": self._is_fitted}
        if not self._is_fitted:
            return state

        # Global price scaler (fallback)
        state["price_scaler_min"] = self._price_scaler.data_min_.tolist()
        state["price_scaler_max"] = self._price_scaler.data_max_.tolist()

        # Per-symbol price scalers
        symbol_scalers = {}
        for sym, scaler in self._symbol_price_scalers.items():
            symbol_scalers[sym] = {
                "min": scaler.data_min_.tolist(),
                "max": scaler.data_max_.tolist(),
            }
        state["symbol_price_scalers"] = symbol_scalers

        # Volume scaler
        state["volume_scaler_min"] = self._volume_scaler.data_min_.tolist()
        state["volume_scaler_max"] = self._volume_scaler.data_max_.tolist()

        # Feature scaler
        state["feature_scaler_min"] = self._feature_scaler.data_min_.tolist()
        state["feature_scaler_max"] = self._feature_scaler.data_max_.tolist()
        state["feature_scaler_range"] = [
            float(self._feature_scaler.feature_range[0]),
            float(self._feature_scaler.feature_range[1]),
        ]
        state["feature_scaler_n_features"] = int(self._feature_scaler.n_features_in_)

        return state

    def _restore_scaler(self, scaler: MinMaxScaler, data_min, data_max, n_features: int = 1) -> None:
        """Restore a MinMaxScaler from serialized min/max arrays."""
        scaler.data_min_ = np.array(data_min)
        scaler.data_max_ = np.array(data_max)
        scaler.data_range_ = scaler.data_max_ - scaler.data_min_
        # Guard against zero-range features (constant columns)
        safe_range = np.where(scaler.data_range_ == 0, 1.0, scaler.data_range_)
        scaler.scale_ = (
            scaler.feature_range[1] - scaler.feature_range[0]
        ) / safe_range
        scaler.min_ = scaler.feature_range[0] - scaler.data_min_ * scaler.scale_
        scaler.n_features_in_ = n_features
        scaler.n_samples_seen_ = 1

    def load_state(self, state: Dict) -> None:
        """Restore ALL scaler states from saved checkpoint data."""
        if not state.get("is_fitted"):
            return

        # Restore global price scaler
        self._restore_scaler(
            self._price_scaler,
            state["price_scaler_min"],
            state["price_scaler_max"],
            n_features=1,
        )

        # Restore per-symbol price scalers
        self._symbol_price_scalers = {}
        for sym, sd in state.get("symbol_price_scalers", {}).items():
            scaler = MinMaxScaler(feature_range=(0, 1))
            self._restore_scaler(scaler, sd["min"], sd["max"], n_features=1)
            self._symbol_price_scalers[sym] = scaler
        if self._symbol_price_scalers:
            logger.debug(
                f"Restored {len(self._symbol_price_scalers)} per-symbol "
                f"price scalers: {list(self._symbol_price_scalers.keys())}"
            )

        # Restore volume scaler
        self._restore_scaler(
            self._volume_scaler,
            state["volume_scaler_min"],
            state["volume_scaler_max"],
            n_features=1,
        )

        # Restore feature scaler for raw indicator columns
        if "feature_scaler_min" in state:
            feat_range = state.get("feature_scaler_range", [-1, 1])
            self._feature_scaler.feature_range = tuple(feat_range)
            expected_n = len(self._RAW_INDICATOR_COLS)
            saved_n = state.get("feature_scaler_n_features", expected_n)

            if saved_n != expected_n:
                logger.warning(
                    f"Feature scaler dimension mismatch: checkpoint has "
                    f"{saved_n} features, expected {expected_n}. "
                    f"Re-train the model to fix this."
                )
            else:
                self._restore_scaler(
                    self._feature_scaler,
                    state["feature_scaler_min"],
                    state["feature_scaler_max"],
                    n_features=saved_n,
                )
                logger.info(
                    "Preprocessor state restored from checkpoint "
                    "(including feature scaler)"
                )
        else:
            logger.warning(
                "Checkpoint missing feature_scaler state — "
                "inference features may not match training. "
                "Re-train the model to fix this."
            )

        self._is_fitted = True
